### ISSUE TITLE
train.py - g_loop - reshape seems wrong.

### ISSUE THREAD

**Issue by xiangjieSui** [DaniMS-ZGZ/ScanGAN360#1]
g_fake_data = torch.reshape(g_fake_data,(b_size, 2, g_fake_data.shape[-1] // 2))
scanpath = torch.reshape(scanpath,(b_size, 2, scanpath.shape[-1] // 2))

It's seems the  ground-truth and fake scanpaths should be 3-dim (xyz). So their shapes should be (b_size, 3, scanpath.shape[-1] // 3).

**Comment by DaniMS-ZGZ** [comment]
Hi!

You are right. Since our data is three-dimensional, the code should be like that. 

I uploaded an older version of the file train.py. I will upload the correct one soon. 

Thanks,
